apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:  
    app: mongodb
spec:
  containers:
  - image: mongo:3.6.12
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc